//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RSAfFile.gjuha {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Al_res {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Al_res() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("RSAfFile.gjuha.Al-res", typeof(Al_res).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Anglisht.
        /// </summary>
        internal static string Anglisht {
            get {
                return ResourceManager.GetString("Anglisht", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dekripto.
        /// </summary>
        internal static string Dekripto {
            get {
                return ResourceManager.GetString("Dekripto", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Duke punuar.
        /// </summary>
        internal static string DukePunuar {
            get {
                return ResourceManager.GetString("DukePunuar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enkripto.
        /// </summary>
        internal static string Enkripto {
            get {
                return ResourceManager.GetString("Enkripto", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gjuha.
        /// </summary>
        internal static string Gjuha {
            get {
                return ResourceManager.GetString("Gjuha", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ky program bene enkriptimin e nje fajlli me RSA. 
        ///Eshte bere me iniciativen e prof. Arbnor Halili.
        ///
        ///Punoj: Arton Hoti
        ///@: arti._@hotmail.com.
        /// </summary>
        internal static string info {
            get {
                return ResourceManager.GetString("info", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Informata rreth projektuesve.
        /// </summary>
        internal static string infoemri {
            get {
                return ResourceManager.GetString("infoemri", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Koha aktuale.
        /// </summary>
        internal static string Kohaaktual {
            get {
                return ResourceManager.GetString("Kohaaktual", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mbyll.
        /// </summary>
        internal static string Mbyll {
            get {
                return ResourceManager.GetString("Mbyll", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zgjedhni celsin duke klikuar shfleto 
        ///Zgjedhni fajllin duke klikuar shfleto
        ///Veproni me enkript apo me dekript..
        /// </summary>
        internal static string ndihm {
            get {
                return ResourceManager.GetString("ndihm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ndihma.
        /// </summary>
        internal static string Ndihma {
            get {
                return ResourceManager.GetString("Ndihma", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sqarime.
        /// </summary>
        internal static string ndihmEmri {
            get {
                return ResourceManager.GetString("ndihmEmri", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ne pritje.
        /// </summary>
        internal static string Nepritje {
            get {
                return ResourceManager.GetString("Nepritje", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Opsione.
        /// </summary>
        internal static string Opsione {
            get {
                return ResourceManager.GetString("Opsione", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Perfundoi.
        /// </summary>
        internal static string perfundoi {
            get {
                return ResourceManager.GetString("perfundoi", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Perfundoj.
        /// </summary>
        internal static string Perfundoj {
            get {
                return ResourceManager.GetString("Perfundoj", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rreth nesh.
        /// </summary>
        internal static string RrethNesh {
            get {
                return ResourceManager.GetString("RrethNesh", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Shfleto.
        /// </summary>
        internal static string Shfleto {
            get {
                return ResourceManager.GetString("Shfleto", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Shqip.
        /// </summary>
        internal static string Shqip {
            get {
                return ResourceManager.GetString("Shqip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Shtegu i celesit:.
        /// </summary>
        internal static string shtegucelsit {
            get {
                return ResourceManager.GetString("shtegucelsit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Shtegu i fajllit.
        /// </summary>
        internal static string shteguifilet {
            get {
                return ResourceManager.GetString("shteguifilet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Statusi:.
        /// </summary>
        internal static string Statusi {
            get {
                return ResourceManager.GetString("Statusi", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enkriptimi/Dekriptimi i nje file me RSA.
        /// </summary>
        internal static string titulli {
            get {
                return ResourceManager.GetString("titulli", resourceCulture);
            }
        }
    }
}
